### ISSUE TITLE
Clustering code is not present

### ISSUE THREAD

**Issue by ShankarChavan** [HansikaPH/time-series-forecasting#5]
I read through your paper and mention of Bandara et al paper were clustering approach was used as a part of pre-processing steps (snob algorithm using MML) and in your code there is cluster_results_merger.py at time-series-forecasting/utility_scripts/error_summary_scripts/clusters_results_merger.py  but no code for clustering. Can you please add clustering code to get an overall understanding of how cluster were generated and used in cluster_results_merger.py

**Comment by HansikaPH** [comment]
@ShankarChavan, in these experiments no clustering was performed by us apart from the default clustering given in certain datasets such as the M3, M4 and CIF2016. The M3 and M4 datasets have the default groups of time series such as Macro, Micro, Finance etc... In the CIF2016 dataset, the grouping was done to separate the two types of time series having forecast horizon 6 and 12. The clusters_results_merger.py merges the results from these default clusters. Other than that, no clustering was performed using snob etc...

**Comment by shankar-taladra** [comment]
Thanks Hansika for clarifying about clustering, just one more doubt can this same idea be used for multivariate time-series?

**Comment by HansikaPH** [comment]
@ShankarChavan The code at the moment cannot be used for multivariate forecasting. Because multivariate forecasting works differently where for the forecasts of every series, are affected directly by the values of some other series. But in our context, every series is forecasted individually while other related series are taken into account when training the weights of the global model.

**Comment by shankar-taladra** [comment]
Thank you so much @HansikaPH
